# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fkhan <fkhan@student.42abudhabi.ae>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/01/01 18:08:21 by fkhan             #+#    #+#              #
#    Updated: 2024/01/21 19:06:34 by fkhan            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME		= ircserv

CXX			= c++
CXXFLAGS	= -Wall -Wextra -Werror -std=c++98 -g
INCFLAGS	= -I$(INC_DIR) -I$(INC_CMD_DIR) -I$(LIBFT_INC) -I$(LIBTCP_INC) -I$(LIBIRC_INC)
LIBFLAGS	= -L ./$(LIBFT_DIR) -lft -L ./$(LIBTCP_DIR) -ltcp -L ./$(LIBIRC_DIR) -lIRC

CFG_DIR		= config
CFG_LOG		= $(CFG_DIR)/ircserv.log

SSL_DIR		= ssl
SSL_CERT	= $(SSL_DIR)/ircserv.crt
SSL_KEY		= $(SSL_DIR)/ircserv.key

LIB_DIR		= lib

LIBFT_DIR	= $(LIB_DIR)/libft
LIBFT_INC	= $(LIBFT_DIR)/inc
LIBFT		= $(LIBFT_DIR)/libft.a

LIBTCP_DIR	= $(LIB_DIR)/libtcp
LIBTCP_INC	= $(LIBTCP_DIR)/inc
LIBTCP		= $(LIBTCP_DIR)/libtcp.a

LIBIRC_DIR	= $(LIB_DIR)/libIRC
LIBIRC_INC	= $(LIBIRC_DIR)/inc
LIBIRC		= $(LIBIRC_DIR)/libIRC.a

INC_DIR		= inc
INC_CMD_DIR	= inc/cmd
SRC_DIR		= src
BUILD_DIR	= .build

SRC			= $(wildcard $(SRC_DIR)/*/*.cpp) $(wildcard $(SRC_DIR)/*.cpp)
INC			= $(wildcard $(INC_DIR)/*/*.hpp) $(wildcard $(INC_DIR)/*.hpp)
OBJ			= $(SRC:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)

# COLORS
GREEN 				= \033[0;32m
RED 				= \033[0;31m
RESET 				= \033[0m

all: $(NAME)

bonus: all

$(NAME): $(LIBFT) $(LIBTCP) $(LIBIRC) $(BUILD_DIR) $(OBJ)
	@$(CXX) $(CXXFLAGS) $(OBJ) $(LIBFLAGS) $(INCFLAGS) -o $(NAME)
	@echo "\n$(NAME): $(GREEN)object files were created$(RESET)"
	@echo "$(NAME): $(GREEN)$(NAME) was created$(RESET)"

$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)
	@mkdir -p $(BUILD_DIR)/cmd
	@echo "$(NAME): $(GREEN)$(BUILD_DIR) was created$(RESET)"

$(BUILD_DIR)/%.o : $(SRC_DIR)/%.cpp $(INC)
	@$(CXX) $(CXXFLAGS) -c $(INCFLAGS) $< -o $@
	@echo ".\cpp"

$(LIBFT):
	@echo "$(NAME): $(GREEN)Creating $(LIBFT)...$(RESET)"
	@$(MAKE) -sC $(LIBFT_DIR)

$(LIBTCP):
	@echo "$(NAME): $(GREEN)Creating $(LIBTCP)...$(RESET)"
	@$(MAKE) -sC $(LIBTCP_DIR)

$(LIBIRC):
	@echo "$(NAME): $(GREEN)Creating $(LIBIRC)...$(RESET)"
	@$(MAKE) -sC $(LIBIRC_DIR)

clean:
	@$(MAKE) -sC $(LIBFT_DIR) clean
	@$(MAKE) -sC $(LIBTCP_DIR) clean
	@$(MAKE) -sC $(LIBIRC_DIR) clean
	@rm -rf $(BUILD_DIR)
	@echo "$(NAME): $(RED)object files were deleted$(RESET)"

fclean: clean
	@rm -f $(LIBIRC)
	@echo "$(NAME): $(RED)$(LIBIRC) was deleted$(RESET)"
	@rm -f $(LIBTCP)
	@echo "$(NAME): $(RED)$(LIBTCP) was deleted$(RESET)"
	@rm -f $(LIBFT)
	@echo "$(NAME): $(RED)$(LIBFT) was deleted$(RESET)"
	@rm -f $(NAME)
	@echo "$(NAME): $(RED)$(NAME) was deleted$(RESET)"

re:
	@$(MAKE) fclean
	@$(MAKE) all

.PHONY: all bonus clean fclean re